<a href="https://colab.research.google.com/github/mon-jas/Educollab-Python-Programming-Workshop/blob/main/Lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is my first time working on a Google collab notebook. It feels pretty cool. 

I'm adding a mathematical equation: 

$ y=m*c $

I have to use pretty much the LaTeX code for writing proper mathematical equations. 

In [ ]:
a = 12
print(a, "is of type", type(a))
print(a, "is integer", isinstance(a,int))

12 is of type <class 'int'>
12 is integer True


In [ ]:
print(type(0xFF))

<class 'int'>


In [ ]:
print(0xFF)

255


In [ ]:
#If a no. is given you have to reverse it 
x=input("Provide a number: ")
a=list(x)
a.reverse()
y="".join(a)
print("Reversed no. is", y)


Provide a number: 2342
Reversed no. is 2432


In [ ]:
a=3+9j
type(a)

complex

for python you have to use j for the imaginary part in complex numbers

In [ ]:
a=complex(3,9)
print(a)

(3+9j)


In [ ]:
print("Real part :", a.real)
print("Imaginary part :", a.imag)
print("Complex conjugate: ", a.conjugate)

Real part : 3.0
Imaginary part : 9.0
Complex conjugate:  <built-in method conjugate of complex object at 0x7f60f3241530>


In [ ]:
print(''' I'm triple lining 
stuff coz it's fun lolzz haha 
oifnf''')

 I'm triple lining 
stuff coz it's fun lolzz haha 
oifnf


In [ ]:
print(a)

(3+9j)


In [ ]:
a="nice"
a.find("i")

1

<h4> Working with numpy </h4>

In [ ]:
import numpy as np
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np_array=np.array(list_of_lists)
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Initialize an array of zeros



In [ ]:
zeros_array=np.zeros((3,2))
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ones_array=np.ones((4,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
nine=np.arange(10)
nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
nine.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np_array.dtype

dtype('int64')

In [ ]:
np_array.shape

(3, 3)

In [ ]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
nine.shape

(10,)

In [ ]:
nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten=nine.reshape(5,2)

In [ ]:
ten

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
ten.shape

(5, 2)

In [ ]:
ten.size

10

In [ ]:
np_array.size

9

In [ ]:
np_array.nbytes

72

In [ ]:
ten.nbytes

80

In [ ]:
np_array=np.array(list_of_lists, dtype=np.int8)

In [ ]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [ ]:
ten

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
ten[2:,:0]

array([], shape=(3, 0), dtype=int64)

In [ ]:
ten[2:,:1]

array([[4],
       [6],
       [8]])

In [ ]:
ten[2:,:2]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np_array=np.arange(9).reshape(3,3)

In [ ]:
np_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np_array1=np.arange(10,19).reshape(3,3)
np_array1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np_array * np_array1

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [ ]:
np_array +np_array1

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [ ]:
np_array.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
np_array.dot(np_array1)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

<h4> Use the Pandas DataFrame

In [ ]:
import pandas as pd
first=['michael','holly','jim','dwight','pam']
last =['scott','schrute','malone','palmer','lol']
ages=[23,232,134,24,13]

df=pd.DataFrame({'first':first,'last':last,'age':ages})
df

first     last  age
0  michael    scott   23
1    holly  schrute  232
2      jim   malone  134
3   dwight   palmer   24
4      pam      lol   13

In [ ]:
df.head(10)

first     last  age
0  michael    scott   23
1    holly  schrute  232
2      jim   malone  134
3   dwight   palmer   24
4      pam      lol   13

In [ ]:
df.head(2)

first     last  age
0  michael    scott   23
1    holly  schrute  232

In [ ]:
df.tail(2)

first    last  age
3  dwight  palmer   24
4     pam     lol   13

In [ ]:
df.describe()

age
count    5.000000
mean    85.200000
std     95.862923
min     13.000000
25%     23.000000
50%     24.000000
75%    134.000000
max    232.000000

In [ ]:
df['first']

0    michael
1      holly
2        jim
3     dwight
4        pam
Name: first, dtype: object

slice a column

In [ ]:
df['first'][3:]

3    dwight
4       pam
Name: first, dtype: object

In [ ]:
df[df['age']>60]

first     last  age
1  holly  schrute  232
2    jim   malone  134

<h4> Use the pandas Series </h4>

In [ ]:
pd_series=pd.Series([1,2,3])
pd_series

0    1
1    2
2    3
dtype: int64

In [ ]:
f"This series is made up of {pd_series.size} items whose data type is {pd_series.dtype}"

'This series is made up of 3 items whose data type is int64'

In [ ]:
pd_series=pd.Series([2,2,3,23])
pd_series

0     2
1     2
2     3
3    23
dtype: int64

In [ ]:
age=df.age
type(age)

pandas.core.series.Series

In [ ]:
pd_series.mean()

7.5

In [ ]:
pd_series.unique()

array([ 2,  3, 23])

In [ ]:
pd_series.max()

23

In [ ]:
pd_series.min()

2